source 'https://github.com/CocoaPods/Specs.git'
platform :ios,	'7.0'
inhibit_all_warnings!
xcodeproj 'MengTodayExtension.xcodeproj'

pod 'Aspects', '~> 1.4.1'
pod 'SVPullToRefresh', '~> 0.4.1'

# Append to your Podfile
# http://samwize.com/2014/05/15/resolving-cocoapods-build-error-due-to-targets-building-for-only-active-architecture/

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end